---
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic
      - path: fixtures/
        linters:
          - lll
      - path: example/
        linters:
          - errcheck
          - gocritic

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
